CREATE TABLE IF NOT EXISTS user_auth_identities (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    provider varchar(32) NOT NULL,
    provider_user_id text NOT NULL,
    provider_email text,
    created_at timestamptz NOT NULL DEFAULT now(),
    last_used_at timestamptz,
    CONSTRAINT user_auth_identities_provider_uid_unique
        UNIQUE (provider, provider_user_id)
);

CREATE INDEX IF NOT EXISTS user_auth_identities_user_id_idx
    ON user_auth_identities (user_id);
